/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Raghav Gupta (https://sketchfab.com/raghav-wd)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pikachu-37c740f674cd4719a1d1d2970bbe8c30
Title: Pikachu
*/
'use client'
import React, { useContext, useEffect, useRef, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { AnimationStore } from '@/app/store/AnimationStore';

export default function Pikachu(props) {
  const {pikaAnimation}=useContext(AnimationStore)
  const size=window.innerWidth<550?1.3:2.5;
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/pika.glb')
  const { actions,names } = useAnimations(animations, group)
  const [past,present]=useState(pikaAnimation);
  useEffect(()=>{
    actions[names[past]].stop();
    actions[names[pikaAnimation]].play();
    present(pikaAnimation)
  })
  return (
    <group ref={group} {...props} dispose={null} scale={size} position={[0.2,-1.5,0]}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh
          name="Object_7"
          geometry={nodes.Object_7.geometry}
          material={materials.Material_160}
          skeleton={nodes.Object_7.skeleton}
          position={[0.006, -0.018, -0.048]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.025}
        />
        <skinnedMesh
          name="Object_8"
          geometry={nodes.Object_8.geometry}
          material={materials['Material.001']}
          skeleton={nodes.Object_8.skeleton}
          position={[0.006, -0.018, -0.048]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.025}
        />
        <skinnedMesh
          name="Object_9"
          geometry={nodes.Object_9.geometry}
          material={materials['Material.003']}
          skeleton={nodes.Object_9.skeleton}
          position={[0.006, -0.018, -0.048]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.025}
        />
        <skinnedMesh
          name="Object_10"
          geometry={nodes.Object_10.geometry}
          material={materials['Material.002']}
          skeleton={nodes.Object_10.skeleton}
          position={[0.006, -0.018, -0.048]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.025}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/pika.glb')
