/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: JPScott1 (https://sketchfab.com/JPScott1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lightning-bolt-d25e29d520a24f8cad9bc58417d70379
Title: Lightning Bolt
*/
'use client'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { DirectionalLight } from 'three';

export default function LightninigBold(props) {
  const scale=window.innerWidth<550?0.0035:0.005
  const { nodes, materials } = useGLTF('/lightning_bolt.glb');
  const groupRef=useRef()
  useFrame((state,delta)=>{
        groupRef.current.rotation.y+=delta*0.2
  })
  return (
    <group {...props} dispose={null} ref={groupRef} rotation={[0,0,0.01]}>
      <group scale={scale}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlane1_phong1_0.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlane1_Material_0_0.geometry}
          material={materials.Material_0}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/lightning_bolt.glb')
